getStudies, Cases, Clinicaldata, mRNA, Mutation
waldronlab/cBioPortalData pull request #54
Opened 2022-04-26 08:06 UTC by kmezhoud

Update of `cgdsMigration.Rmd` file

2022-04-26 13:57 UTC, LiNk-NY requested changes
Hi Karim, @kmezhoud 
Thanks for following up. 
Please see my comments in the diff and let me know if you have questions. 
Best regards,
Marcel

2022-04-26 13:57 UTC, LiNk-NY commented on vignettes/cgdsMigration.Rmd
> +if (!require("tictoc")) install.packages("tictoc")
Don't provide installation functions in the vignette. Please see other vignettes in the package as examples. Avoid the use of additional packages such as `DT` and `tictoc`. The code should be using the native pipe operator `|>`, if at all.

2022-04-26 13:57 UTC, LiNk-NY commented on vignettes/cgdsMigration.Rmd
> -library(cBioPortalData)
Please restore deleted chunks. These are relevant to the vignette.

2022-04-26 13:57 UTC, LiNk-NY commented on vignettes/cgdsMigration.Rmd
> +    datatable(options = list(pageLength = 5))
Do not evaluate `cgdsr` code chunks. This package is defunct and not available on CRAN. The code provided is for demo purposes only.

2022-04-26 13:57 UTC, LiNk-NY commented on vignettes/cgdsMigration.Rmd
> -# Obtaining Cases and Clinical data
Do not delete headers and keep the structure of the original vignette for easy lookup.

2022-04-26 13:57 UTC, LiNk-NY commented on vignettes/cgdsMigration.Rmd
> +* Each patient can participate to one or multiple assays. This means that we can find a `case_id` in multiple `case_list_id`. This is suitable for both `cgdsr` and `cBioPortalData`.
Please wrap lines > 80 char width

2022-04-26 13:57 UTC, LiNk-NY commented on vignettes/cgdsMigration.Rmd
> +* Marcel, WHEN WE CAN USE THIS ENDPOINTS? It does not returns Clinical data tibble.
Remove these comments. Please ask in a new issue.

2022-04-26 13:57 UTC, LiNk-NY commented on vignettes/cgdsMigration.Rmd
> +* **`cBioPortalData` cannot query with `sampleListId` to get a subset of sample list.**
Yes, it can. Also, you can look up the sample identifiers with `samplesInSampleLists(cbio, "gbm_tcga_pub_expr_classical")`

2022-04-26 13:57 UTC, LiNk-NY commented on vignettes/cgdsMigration.Rmd
> +* `cBioPortalData` returns `sampleId` (TCGA-02-0009-01) & `patientId` (TCGA-02-0009). It uses **dash** instead **dot**.
This is how the data is provided from the API.

2022-04-26 13:57 UTC, LiNk-NY commented on vignettes/cgdsMigration.Rmd
> +It require a `cBioPortalData` version >= `2.7.11`.
This is not necessary. It will be available to all Bioconductor users in the next release and current devel users.

2022-04-26 13:57 UTC, LiNk-NY commented on vignettes/cgdsMigration.Rmd
> +NOT WORKING
This is working. Please remove misleading statements.

2022-04-26 13:57 UTC, LiNk-NY commented on vignettes/cgdsMigration.Rmd
> +    #by = "hugoGeneSymbol",
Remove commented code

2022-04-26 13:57 UTC, LiNk-NY commented on vignettes/cgdsMigration.Rmd
> +### Three ways to get molecular Data
Is this for mutation data?

2022-04-26 13:57 UTC, LiNk-NY commented on vignettes/cgdsMigration.Rmd
> +NOT WORKING
Again, this is working. Please check your version of `cBioPortalData` and make sure it is the latest.

2022-04-26 13:57 UTC, LiNk-NY commented on vignettes/cgdsMigration.Rmd
> +searchOps(cbio, "gene")
This section is not necessary. Please remove.

2022-04-26 13:57 UTC, LiNk-NY commented on vignettes/cgdsMigration.Rmd
> -gbm_pub <- cBioPortalData(
Restore this section.

2022-04-27 14:03 UTC, LiNk-NY commented
Hi Karim, @kmezhoud 
Thank you for making those changes! It's looking good. 
Best,
Marcel

2022-04-27 16:14 UTC, LiNk-NY commented
Thanks again!
I've merged the changes and made some updates.
I had to resolve a lot of conflicting files in the merge. Hopefully I did it right. 
Best,
Marcel

2022-04-27 16:45 UTC, merged

2022-04-27 16:45 UTC, kmezhoud commented
Dear Marcel,  @LiNk-NY 
If you want I can add sections for Methylation and CNA.
It seems the same format than `mRNA` , just user needs to change the right  `molecularProfileIds`.
Karim

2022-04-27 16:48 UTC, LiNk-NY commented
Hi Karim, @kmezhoud 
You can if you'd like.
Make sure you are working off the latest `devel` branch to avoid messy merges. :) 
I've fixed the commit history as best I could. 
Best regards,
Marcel